services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    env_file:
      - path: .env
        required: false
    volumes:
      - ./app/src:/app/src
      - ./app/tsconfig.json:/app/tsconfig.json
      - ./app/package.json:/app/package.json
      - ./app/package-lock.json:/app/package-lock.json
      - ./app/newrelic.cjs:/app/newrelic.cjs
