app = 'luanupe'
primary_region = 'gru'
swap_size_mb = 512

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'
  DEBUG_LOGS = 'false'
  PORT = '3000'
  CACHE_TTL = '1h'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    method = 'GET'
    path = '/health'
    interval = '30s'
    timeout = '5s'
    grace_period = '30s'

[[vm]]
  size = 'shared-cpu-1x'
