worker_processes auto;
error_log /dev/stderr warn;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    client_body_temp_path /tmp/nginx-client-body;
    proxy_temp_path       /tmp/nginx-proxy;

    server_tokens off;
    gzip off;
    sendfile        on;
    keepalive_timeout  65;

    set_real_ip_from 172.16.0.0/16;
    set_real_ip_from fdaa::/16;
    real_ip_header Fly-Client-IP;
    real_ip_recursive on;

    map $http_cf_connecting_ip $client_real_ip {
        "" $remote_addr;
        default $http_cf_connecting_ip;
    }

    log_format main '$client_real_ip - $remote_user [$time_local] '
                    '"$request" $status $body_bytes_sent '
                    '"$http_referer" "$http_user_agent" '
                    'remote_addr="$remote_addr" '
                    'cf_connecting_ip="$http_cf_connecting_ip" '
                    'fly_client_ip="$http_fly_client_ip" '
                    'xff="$http_x_forwarded_for" '
                    'realip_remote_addr="$realip_remote_addr"';

    access_log /dev/stdout main;

    limit_req_zone $client_real_ip zone=per_ip:10m rate=3r/s;

    server {
        listen 8080;
        server_name _;
        limit_req_status 429;

        location ~* /(\.env|\.ht|\.git|\.gitignore|\.svn|\.hg|\.bzr|.*\.ya?ml$|.*\.sql(\..*)?$|.*\.php\..*|.*\.inc$|.*\.bak$|.*\.backup$|.*\.swp$|.*\.swo$|.*\.tmp$|.*\.old$|.*\.orig$|.*\.log$|.*\.db$|.*\.sqlite3?$|.*\.pem$|.*\.key$|.*\.crt$|.*\.psd$|.*\.ai$|.*\.conf$|\.user\.ini|Dockerfile|docker-compose\.ya?ml|\.dockerignore|id_rsa|id_ecdsa|id_ed25519|id_dsa)(/|$) {
            access_log off;
            deny all;
        }

        location = /warmup {
            access_log off;
            return 423;
        }

        location / {
            limit_req zone=per_ip burst=10 nodelay;

            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $client_real_ip;
            proxy_set_header X-Forwarded-For $client_real_ip;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_pass http://127.0.0.1:3000;
        }
    }
}
